# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Noir < Formula
  desc "♠️ noir is an attack surface detector form source code"
  homepage "https://github.com/hahwul/noir"
  url "https://github.com/hahwul/noir/archive/v0.8.0.tar.gz"
  sha256 "4c8abef3fe3dec3852750c60303ba6f58e6c09a7bb13e9a42c7d208fb5af1bfd"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
system "shards build --release --no-debug --production"
bin.install "bin/noir"
  end

  test do
    system "{bin}/noir", "-v"
  end
end
