# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Noir < Formula
  desc "♠️ noir is an attack surface detector form source code"
  homepage "https://github.com/hahwul/noir"
  url "https://github.com/hahwul/noir/archive/v0.5.0.tar.gz"
  sha256 "59f26cb02e2f697602d477fd2b34da737b9a472facfcda0e15b1d90b68bdb420"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
system "shards build --release --no-debug --production"
bin.install "bin/noir"
  end

  test do
    system "{bin}/noir", "-v"
  end
end
