# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Noir < Formula
  desc "♠️ noir is an attack surface detector form source code"
  homepage "https://github.com/hahwul/noir"
  url "https://github.com/hahwul/noir/archive/v0.5.3.tar.gz"
  sha256 "2be7d5a50f9f3382110fb44d9782a7e0676fc2e84571d0e4d07588a7c7e37f29"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
system "shards build --release --no-debug --production"
bin.install "bin/noir"
  end

  test do
    system "{bin}/noir", "-v"
  end
end
